# Generated by Django 2.2.19 on 2021-03-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
    ]
