# Generated by Django 3.1.7 on 2021-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210311_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ex_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
