# Generated by Django 2.2.19 on 2021-03-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210309_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, db_column='addr', max_length=50, null=True, verbose_name='Адрес'),
        ),
    ]
