# Generated by Django 2.2.19 on 2021-03-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210309_1511'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publisher',
            table='publishers',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publisher', models.ForeignKey(blank=True, db_column='publisher_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Publisher', verbose_name='Издатель')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
